name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Get current version
        id: current_version
        run: |
          echo "version=$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Bump version
        run: |
          uv version --bump ${{ github.event.inputs.release_type }}
          uv lock --upgrade-package msg91-py

      - name: Get new version
        id: new_version
        run: |
          echo "version=$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and tag version bump
        run: |
          git add pyproject.toml uv.lock
          git commit -m "Bump version to ${{ steps.new_version.outputs.version }}"
          git tag -a v${{ steps.new_version.outputs.version }} -m "Version ${{ steps.new_version.outputs.version }}"

      - name: Push commit and tag
        run: |
          git push
          git push origin v${{ steps.new_version.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.new_version.outputs.version }}
          name: Release v${{ steps.new_version.outputs.version }}
          generate_release_notes: true
